import { Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import TopBar from "./Components/top-bar";
import Navbar from "./Components/nav-bar";
import FooterSection from "./Components/footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${playfair.variable} antialiased`}
      >
        <TopBar />
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
